### ISSUE TITLE
Problema ao carregar arquivo TSV

### ISSUE THREAD

**Issue by joaovitorez** [octos-ai/octos-academy#10]
No exercício 1 de Data Handling eu não estou conseguindo carregar o arquivo, nem mesmo. O erro diz que o arquivo não existe, mesmo ele estando no caminho que coloquei. 

Tentei dois métodos: pd.read_csv e read.table.

**O código:** 
```
import numpy as np
import pandas as pd

food = pd.read_csv('C:\Users\joaov\Desktop\TreinamentoOctosAI')
```

**O erro:**

IOError: [Errno 2] File C:\Users\joaov\Desktop\TreinamentoOctosAI does not exist: 'C:\\Users\\joaov\\Desktop\\TreinamentoOctosAI'

**Comment by joaovitorez** [comment]
Pessoal, sigo com um problema para carregar o arquivo. 

Consegui fazer o esquema de baixar o arquivo do kaggle instalando ele no Jupyter, etc, mas to tendo com alguns problemas.

O primeiro é que eu não estou conseguindo rodar a parte de fazer o download usando o API key do kaggle. Lá diz que não foi achado um arquivo .kaggle/kaggle.json no meu repositório sendo que acessando o repositório eu consigo vê-lo lá.

O segundo é que to tendo alguns problemas de permissão também. Ele não me permite por exemplo salvar o arquivo kaggle.json dentro do meu repositório /home/joaovitorez, não sei o porquê, porém ele me deixa salvar o arquivo num repositório World_Food_Facts/.kaggle, que por sua vez tá dentro de /home/joaovitorez.

Eu já testei algumas hipóteses para esses problemas mas nada resolve:

1. O problema poderia ser porque na hora de instalar o jupyter, eu o instalei quando já estava na pasta dos arquivos, e não no início, quando estou em /home/joaovitorez. Sendo assim, eu voltei p essa parte do repositório, instalei o jupyter ali e depois reiniciei o jupyter, mas não resolveu problema.

2. Também já tentei mudar chaves de permissão dos arquivos com chmod 777 (que libera a permissão p tudo p todo mundo), mas o jupyter reclama disso e manda eu mudar. Então eu mudo para chmod 600, e ai quando tento fazer o download ele me diz que eu não tenho autorização para fazer o download (lembrando que o arquivo .kaggle/kaggle.json fica com "rw-", ou seja, teoricamente eu não posso executar mesmo, mas pelo menos com Igor funcionava mesmo assim). De qualquer maneira, com chmod 777 deveria ter funcionado eu acho.

@igormq @lpcinelli vocês conseguem ajudar?

O link para a última modificação que eu fiz tá [nesse link](https://github.com/joaovitorez/octos-academy/blob/branch-exercicio1/02.%20Data%20Handling/Exercises/01_Getting_%26_Knowing_Your_Data/World%20Food%20Facts/Exercises.ipynb).

**Comment by igormq** [comment]
Ótima _issue_, João. :)

Vamos lá. Primeiro que eu vi é que você está criando a pasta em

```bash
mkdir -p World_Food_Facts/.kaggle
```
mas na verdade, a pasta `.kaggle` tem que ser criada na `home` (isto é, `~/` ou `$HOME`). Então o comando certo seria:

```bash
mkdir -p ~/.kaggle
```

Quanto a instalação do Jupyter, não importa onde você instala (isto é, usando o comando `conda install jupyter`, desde que você esteja certinho dentro do seu environment `conda activate seu-environment`). Agora, o que realmente importa, é de onde você executa o Jupyter (quando você digita `jupyter notebook`), porque ali vai ser sua pasta padrão (e você vai ter acesso as pastas que estão ali dentro, não do lado de fora).

E de acordo com o `ipython`: 

> 
> As explained in https://github.com/ipython/ipython/issues/7751, it is not possible to navigate to the parent directory for security reasons:
> 
>     The kernel might not be python, nor on the same machine than the server, nor do you need a running kernel to use server API(s).
> 
> If you want, you can ask for more information in the aforementioned GitHub issue.
> 

Minha dica é fazer isso pela linha de comando (terminal) ao invés de dentro do jupyter notebook (até porque mover esse arquivo só se faz uma vez).

Te ajudei?

**Comment by joaovitorez** [comment]
Esclareceu muito!!! Agora acho que tive o estalo:

Quando imaginei que tivesse que colocar o kaggle.json na home, eu fiz um !cp mnt/[...] /home/joaovitorez/.kaggle, mas nas diversas tentativas ele dizia que eu não tinha permissão (o que eu achei que pudesse ser por causa dos changes mode (chmod)). Mas agora pelo que você falou, acredito que a falta de permissão era justamente porque não tinha como acessa a home pelo jupyter, porque eu o iniciei já na pasta de exercício. Está realmente fazendo sentido!

Estou recomeçando pelo terminal e digo se funcionou.

**Comment by joaovitorez** [comment]
![image](https://user-images.githubusercontent.com/57195701/85166533-ccfb6c80-b23d-11ea-839b-b96ff30f5b76.png)

Recaí no mesmo problema que tava tendo, infelizmente. Veja que ao rodar ``ls -al /home/joaovitorez/.kaggle``, o arquivo kaggle.json aparece lá, mas quando vou fazer o download ele diz que não está. Enquadrei na imagem tudo que eu fiz a partir do `` pip install -q kaggle``.

**Comment by igormq** [comment]
Conseguiu resolver? Que loucura acontecer isso. Mas você estava no environment certinho?

**Comment by joaovitorez** [comment]
Tava tudo certinho. Até expirar e criar novo API eu fiz pra tentar resolver
mas não consegui.

Mas hoje mesmo Larissa deu a ideia de extrair o arquivo do zip no próprio
windows, e passar o arquivo tsv p repositório do linux pelo terminal,
usando o cp, lá na pasta dos exercícios, e aí foi só usar pd.read_csv no
jupyter que deu certo. Acabou saindo mais fácil ainda!

**Comment by igormq** [comment]
Perfeito! Vou fechar a issue!
