### ISSUE TITLE
Problema para enviar o Exercício 1

### ISSUE THREAD

**Issue by larissagabriela** [octos-ai/octos-academy#12]
Eu estou a um tempo tentando enviar o Exercício 1, mas quando eu dou git push o comando fica muito tempo rodando sem sair dos 47%. 

Usei o comando abaixo: (respondendo-exercícios foi a branch que eu criei para o exercício)
`git push origin respondendo-exercícios`

O resultado:
`Enumerating objects: 40, done.
Counting objects: 100% (40/40), done.
Delta compression using up to 4 threads
Compressing objects: 100% (31/31), done.
Writing objects:  47% (16/34), 189.36 MiB | 58.00 KiB/s`

Já repeti o processo algumas vezes e sempre fica parado nos 47%.
Quando entro git log todos os commits estão lá certinho. 
Entrei em contato com o João e aparentemente segui os mesmos passos que ele sendo que ele não teve esse problema.

**Comment by igormq** [comment]
Problema foi resolvido!
O que aconteceu foi que foi adicionado um arquivo muito grande para dentro do GIT, causando lentidão e impedindo que fosse enviado antes de terminar o timeout. 

A @larissagabriela removeu o arquivo do histórico (utilizando o git rm --cached && git commit --amend CHEAD) e conseguiu, com sucesso, enviar a branch.
