### ISSUE TITLE
Dúvida no comando do step 4 - Exercício da seção 02.02.01 (Chipotle)

### ISSUE THREAD

**Issue by joaovitorez** [octos-ai/octos-academy#15]
Pessoal, eu e Larissa (não consegui marcá-la aqui) chegamos a uma divergência no resultado do step 4 desse exercício e a questão acaba não esclarecendo qual deve ser nosso raciocínio para resolvê-la. Então gostaríamos de saber de vocês, @lpcinelli @igormq , qual vocês acham que seria a melhor ideia para resolver.

Link do exercício [aqui](https://github.com/octos-ai/octos-academy/blob/master/02.%20Data%20Handling/Exercises/02_Filtering_%26_Sorting/Chipotle/Exercises.ipynb)
---

Dataset da questão
---

![image](https://user-images.githubusercontent.com/57195701/85889401-c632a380-b7c1-11ea-8ca7-90879a963c9c.png)

Dúvida da questão `Step 04: How many products cost more than $10.00?`
---

Nesse dataset, existem vários produtos, mas alguns mesmos produtos divergem em preço, uma vez que possuem um *choice_description* diferente, o que pode levar a preços diferentes, como é possível ver no anexo abaixo. A dúvida é: devemos distinguir os produtos apenas pelo que está no *item_name*, ou distingui-los considerando o *item_name* e *choice_description*? Essa distinção é importante para conseguirmos saber quantos produtos distintos custam mais de 10 dólares. Cada uma dessas opções gerou um resultado diferente, sendo o segundo maior que o primeiro.

O que vocês acham que seria melhor fazer? 

Anexo
---

![image](https://user-images.githubusercontent.com/57195701/85890162-35f55e00-b7c3-11ea-844e-80edb850c940.png)

**Comment by araujomarins** [comment]
Oi @joaovitorez, eu acho que as duas soluções são válidas. Eu ainda adicionaria uma terceira interpretação: identificar um produto pela combinação do item_name com o primeiro elemento do choice_description (sem ser o que está dentro da lista).

Eu particularmente escolheria identificar pelo item_name e falar que o preço daquele produto é o menor da lista.  Eu pensei no McDonalds por exemplo, lá se você chegar vai ver que o preço do hambúrguer é 10 reais, mas você pode adicionar bacon por 1 real, ovo por 2, e por aí vai. Apesar de existir combinações com preços maiores, se eu tivesse que atribuir um valor pro hambúrguer eu falaria 10 hahaha

**Comment by lpcinelli** [comment]
Concordo com o Matheus, existe espaço para interpretações e por isso não há uma única resposta correta. O mais importante é o procedimento pelo qual chegaram as respostas (e o raciocínio, que está afiado!).

No meu caso, por exemplo, consideraria o item_name e o choice_description juntos para identificar um produto. Essencialmente, se o nome é igual mas os constituintes são diferentes então não os os mesmos, como a salada do print (podemos imaginar aqui 2 produtos similares de marcas concorrentes tentando se diferenciar). Se os ingredientes são os mesmos, mas o nome diferente então o modo de prepraro/embalagem/posicionamento da marca poderiam torná-lo distinto.

Como podem ver, nem eu e @araujomarins concordamos hahaha.
