### ISSUE TITLE
Dúvida no exercício Getting Financial Data

### ISSUE THREAD

**Issue by larissagabriela** [octos-ai/octos-academy#29]
Oi, pessoal! Tudo bem?
No Step 4, do exercício Getting Financial Data da parte de Time Series, pede para ler os dados do Google. Eu e João não entendemos quais são e como encontrar esses dados.

`Step 4. Read the data from google, assign to df and print it`

**Comment by lpcinelli** [comment]
Realmente, o exercício não deu uma dica sequer. Usem o pacote [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/#indices-and-tables)

```python
import pandas as pd
import datetime
import pandas_datareader.data as web

start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2017, 1, 11)

df = web.DataReader(['AAPL', 'GE', 'GOOG', 'IBM', 'MSFT'], 'yahoo', start=start, end=end)
```
