### ISSUE TITLE
Alteração de pacotes - Tópico de Machine Learning

### ISSUE THREAD

**Issue by joaovitorez** [octos-ai/octos-academy#30]
E aí, pessoal,

Estava criando um novo environment ontem para esse capítulo do treinamento e aparentemente tem um errinho nos pacotes, na parte do Jupyter Client. No READ.ME tá:

```
- python==3.6.4
- numpy==1.13.3
- scipy==1.0.0
- matplotlib==2.1.2
- jupyter==1.0.0
- jupyter-client==5.0.1
```
Porém fica dando erro, e pesquisando, resolvi tentar `jupyter_notebook==5.2.3` que é a versão mais nova e o nome contém underline, em vez de hífen, e aí deu bom!

**Comment by igormq** [comment]
@araujomarins

**Comment by araujomarins** [comment]
Fala @joaovitorez! Bom, nesse momento do READ.ME ele está falando quais são os packages que ele utiliza no environment, logo depois ele fala sobre o environment.yml. Com o comando:

 `conda env create -f environment.yml
`
Rodando aqui e depois listando os packages do environment criado da para ver o "jupyter-client    6.1.6".

**Comment by joaovitorez** [comment]
Cara, na verdade eu não tinha visto que o arquivo tava dentro da pasta dos exercícios hahaha, perdão! Ai na época eu Ao busquei outra alternativa, criando um env.txt via vim pelo terminal, copiei os pacotes nele, e ai coloquei `-f env.txt`, e ai veio o problema que coloquei na issue. Mas está tudo sob controle então haha.
